### ISSUE TITLE
from conf.augment_constant import language_short_tencent

### ISSUE THREAD

**Issue by TolicWang** [yongzhuo/nlp_xiaojiang#1]
from conf.augment_constant import language_short_tencent 这个包在哪儿下载？

**Comment by yongzhuo** [comment]
没有包，只是一些常量值，就是语言的缩写
language_short_tencent = ['en', 'fr', 'ru', 'de', 'es', 'pt',      'jp', 'ko', 'vi', 'id', 'it', 'kr', 'tr', 'ms', 'th']
你下完整的工程里边就有
