### ISSUE TITLE
should delete the 'not' ,,and be like this 'if len(word_syn[0]) else [word]', because the output of the nearby(word) is a tuple include 2 lists

### ISSUE THREAD

**Issue by tecufly** [yongzhuo/nlp_xiaojiang#14]
https://github.com/yongzhuo/nlp_xiaojiang/blob/d4a94149a5b4fd03053850f215edc7745c35af3e/AugmentText/augment_eda/enhance_eda_v2.py#L60

**Comment by yongzhuo** [comment]
thanks, I will fix it.
