### ISSUE TITLE
'Node' object has no attribute 'output_masks'

### ISSUE THREAD

**Issue by ryan-gz** [yongzhuo/nlp_xiaojiang#16]
您好，感谢分享您的项目。
我在尝试运行./FeatrureProject/bert/extract_keras_bert_feature，初始化KerasBertVector遇到了报错：'Node' object has no attribute 'output_masks'，查询网上的方案是将tensorflow 和 keras的layer统一，请问具体应该在哪里修改，解决这个问题，感谢

**Comment by yongzhuo** [comment]
版本问题，requirements.txt全部使用==
如，keras-bert==0.41.0,  keras-bert后边的版本为了支持tf 2.x，导致不兼容前面的版本了

应该是版本问题，必须要如下版本，不支持tf2
tensorflow-gpu==1.12.0-1.15.0
keras==2.2.4
