### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide   matrix_org_norm = (matrix_org / np.sqrt((matrix_org ** 2).sum(-1))[..., np.newaxis]).astype(numpy_type)

### ISSUE THREAD

**Issue by lxz1992** [yongzhuo/nlp_xiaojiang#2]
run chatbot_sentence_vec_by_word.py 这个文件后，会报出警示:RuntimeWarning: invalid value encountered in true_divide matrix_org_norm = (matrix_org / np.sqrt((matrix_org ** 2).sum(-1))[..., np.newaxis]).astype(numpy_type)
且输入不同的字符得到相同的答案，是不是most_similar_sentence_vec这个函数有问题呢。

**Comment by yongzhuo** [comment]
@lxz1992 工程里边词向量只有500条，基本都是OOV，所以得到相同的答案，你需要下载完整的词向量模型；然后因为设置了 if os.path.exists(matrix_ques_path_word): 所以每次你想重新跑的时候，你需要到工程的Data/sentence_vec_encode_word目录下删掉生成的1.txt文件，这个判断条件你也可以删掉

**Comment by yongzhuo** [comment]
RuntimeWarning已修复，详情请更新代码!
