### ISSUE TITLE
回译中文本丢失

### ISSUE THREAD

**Issue by zhongwei-yao** [yongzhuo/nlp_xiaojiang#4]
您好，我输入的句子为："**此外，李奇霖还认为，MLF期限是6个月，逆回购是7天，考虑到外汇占款流出的是长期限流动性，因此，无论哪一种货币投放模式都无法替代降准，降准的期限理论上是“无穷期”的。从资金利率看，MLF资金利率在3.35%，比起降准释放的“无成本”流动性仍然偏高，经济下行压力之下，实体能提供的高收益资产有限，较高的资金利率能否缓解外汇占款对信用派生的收缩作用，也是有疑虑的。“等汇率端稍见稳定后，我们能看到降准的出现，幅度约为100BP，时点预计在9月上旬。**" 输出变成了“**此外，李其林还认为MLF期限为6个月，反向回购期为7天。**”

**Comment by yongzhuo** [comment]
bug已修复，原因是谷歌翻译是截断分句翻译的，具体可以看open_url函数中的print(res.text)
谷歌翻译有限制，可参考github项目:https://github.com/skywind3000/translator
修复后的返回结果如下:
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\MOYONG~1\AppData\Local\Temp\jieba.cache
Loading model cost 0.750 seconds.
Prefix dict has been built succesfully.
en False
此外，李其林还认为MLF期限为6个月，反向回购期为7天。考虑到外汇账户没有长期流动性，无论哪种货币交付模式都无法取代存款准备金率，存款准备金率下调。该术语在理论上是“无限的”。从资本利率的角度来看，多边基金的基金利率为3.35％，仍然高于存款准备金率下调的“无成本”流动性。在经济下行压力下，该实体可以提供的高收益资产是有限的，资本利率较高可以对减轻信用衍生品外汇支付收缩存在疑虑。 “在汇率略有企稳后，我们可以看到存款准备金率大约为100BP。时间预计将在9月初。
fr False
此外，李其林还认为，MLF的持续时间为6个月，回购时间为7天。该术语在理论上是“无限的”。就资本利率而言，多边基金的利率为3.35％，仍高于存款准备金率下调所释放的“无成本”流动性。对于缓解信贷衍生品外币支付收缩的担忧也存在疑问。 “一旦汇率小幅企稳，我们可以看到存款准备金率接近100个基点。预计将在9月初。
ru False
此外，李梓林还认为MLF期限为6个月，反向回购期为7天。鉴于货币账户没有长期流动性，无论哪种货币交付模式都无法取代存款准备金率，存款准备金率会下降。这个词在理论上是“无限的”。就资本利率而言，多边基金基金的利率为3.35％，仍高于因存款准备金率下调而释放的无成本流动性。对于放宽信贷衍生工具外币支付的减少也存在疑问。 “在汇率稳定一点后，我们可以观察到存款准备金率，即大约100个基点。预计9月初的时间。
de False
此外，李其林认为，多边基金截止日期为6个月，反向还款期为7天。鉴于外汇账户不再具有长期流动性，无论哪种现金交付模式无法取代存款准备金率，存款准备金率都会降低。该术语在理论上是“无限的”。从资本利率的角度来看，多边基金利率为3.35％，仍高于存款准备金率下调所释放的流动性。在经济下行压力下，公司可以提供的高收益资产有限，资本利率上限可能有限。对减少信用衍生品外币支付下降也存在疑虑。 “在汇率小幅走稳后，我们可以看到存款准备金率大约为100个基点，预计将在9月初。
