### ISSUE TITLE
translate_google.py

### ISSUE THREAD

**Issue by xjtupy** [yongzhuo/nlp_xiaojiang#5]
你好，我这边运行这个文件，报了这个错：ConnectResetError:远程主机强迫关闭了一个现有连接。
是怎么回事啊。

**Comment by yongzhuo** [comment]
访问量大的话会禁止访问，似乎是每天一个IP只有几千次访问。还有可能是防火墙、网络原因等

**Comment by xjtupy** [comment]
网络方面没有问题，访问量是挺大的，但我现在需要这么大的访问量，该怎么解决呢




------------------ 原始邮件 ------------------
发件人: "yongzhuo"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 晚上8:58
收件人: "yongzhuo/nlp_xiaojiang"<nlp_xiaojiang@noreply.github.com>;
抄送: "时间煮雨"<1298817052@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yongzhuo/nlp_xiaojiang] translate_google.py (#5)




访问量大的话会禁止访问，还有可能是防火墙、网络原因等

**Comment by yongzhuo** [comment]
换IP，注册，或者使用国内免费的在线翻译。。。
