### ISSUE TITLE
NER问题咨询

### ISSUE THREAD

**Issue by FankLi** [yongzhuo/nlp_xiaojiang#8]
欧美和台湾经济怎么样
`['O', 'B-LOC', 'I-LOC', 'O', 'B-LOC', 'I-LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']`

为什么预测结果第一位一直是 ‘O’?

还有`keras_bert_ner_bi_lstm.py`，最后一层是CRF吧？因为你的READ.me上面写了：`- layer_crf_bojone.py(CRF层, 未使用)`，让我有点迷惑

期待并感谢你的回复！！！

**Comment by yongzhuo** [comment]
1. 为什么预测结果第一位一直是 ‘O’?
这里是bert-encode的时候加了 [CLS]、[SEP]的原因

2.layer_crf_bojone.py(CRF层, 未使用)
这里是使用了keras-team版本的CRF，而不是苏剑林版本的。这些CRF似乎都有一个问题，bert-embedding+CRF的时候，loss会变为负数，之前我看Kashgari项目的也没有解决。

**Comment by FankLi** [comment]
> 1. 为什么预测结果第一位一直是 ‘O’?
>    这里是bert-encode的时候加了 [CLS]、[SEP]的原因
> 
> 2.layer_crf_bojone.py(CRF层, 未使用)
> 这里是使用了keras-team版本的CRF，而不是苏剑林版本的。这些CRF似乎都有一个问题，bert-embedding+CRF的时候，loss会变为负数，之前我看Kashgari项目的也没有解决。

好的明白了
你的这个版本确实loss为负数，苏剑林版本正常
