### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by xycim** [yongzhuo/nlp_xiaojiang#9]
代码很精彩，对初学者非常友好。感谢作者。
一个疑问，我该如何运行代码呢？
我下载代码后按照说明执行后，然后进入nlp_xiaojiang-master\ClassificationText\bert里面，
执行python keras_bert_classify_bi_lstm.py
报错找不到ModuleNotFoundError: No module named 'conf.path_config'  。我看了代码目录结构，是因为因为bert这个文件夹下没有conf文件夹。conf文件夹在最外层。这个问题如何解决呢？是不是执行代码位置不对？

**Comment by yongzhuo** [comment]
在keras_bert_classify_bi_lstm.py 头文件添加

```
import sys
import os
# base dir
path_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
dir_project = path_root.replace('\\', '/')
sys.path.append(dir_project)
```

**Comment by Fheon** [comment]
import sys
import os
# base dir
path_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
dir_project = path_root.replace('\\', '/')
sys.path.append(dir_project)

it doesn't work
